apiVersion: v1
kind: Service
metadata:
  name: kong-ingress-controller
  namespace: default
spec:
  selector:
    app: kong-ingress-controller
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
    - name: https
      protocol: TCP
      port: 8444
      targetPort: 8444
